services:

  postgres:
    image: postgres:17-alpine

    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5434:5432"
    restart: unless-stopped

  identity-provider:
    image: 127.0.0.1:5000/idp:latest
    volumes:
      - init-scripts:/app/init-scripts
    build:
      context: ./app
    ports:
      - "8004:8000"
    env_file:
      - .env
    depends_on:
      - postgres
    restart: unless-stopped

    healthcheck:
      test: [ "CMD",
              "python",
              "-c",
              "from urllib.request import urlopen; urlopen('http://127.0.0.1:8000/api/health/liveness')" ]
      interval: 20s
      timeout: 5s
      retries: 3
      start_period: 5s

volumes:
  postgres_data:
  init-scripts: