name: Deploy Service

on:
  push:
    branches:
      - main
      - dev

jobs:

  build:
    runs-on: debian

    defaults:
      run:
        shell: sh

    steps:
      - name: Clone repository
        run: git clone http://100.110.100.100:3030/${{ gitea.repository }}.git .

      - name: Build Docker image
        run: |
          docker build \
          --platform linux/arm64 \
          -t 127.0.0.1:5000/idp:latest \
          ./app

      - name: Push Docker image
        run: docker push 127.0.0.1:5000/idp:latest

  deploy:
    needs: build

    runs-on: debian

    defaults:
      run:
        shell: sh

    steps:
      - name: Clone repository
        run: git clone http://100.110.100.100:3030/${{ gitea.repository }}.git .

      - name: Create .env
        run: |
          cat > .env << EOF
          JWT_PRIVATE=${{ secrets.JWT_PRIVATE }}
          JWT_PUBLIC=${{ secrets.JWT_PUBLIC }}
          JWT_ALGORITHM=RS256

          DB_PASSWORD=${{ secrets.DB_PASSWORD }}

          DB_DSN=postgresql+asyncpg://postgres:${{ secrets.DB_PASSWORD }}@postgres:5432/identity_provider
          EOF

      - name: Deploy
        run: docker compose up -d
