name: Deploy Service

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: debian

    defaults:
      run:
        shell: sh

    steps:
      - name: Clone repository
        run: git clone ${{ gitea.server_url }}/${{ gitea.repository }}.git .

      - name: Build Docker image
        run: |
          docker build \
          --platform linux/arm64 \
          -t 127.0.0.1:5000/idp:latest \
          ./app

      - name: Push Docker image
        run: docker push 127.0.0.1:5000/idp:latest

  deploy:
    needs: build

    runs-on: debian

    defaults:
      run:
        shell: sh

    steps:
      - name: Clone repository
        run: git clone ${{ gitea.server_url }}/${{ gitea.repository }}.git .

      - name: Create .env
        run: |
          cat > .env << EOF
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          EOF

      - name: Deploy
        run: docker compose up -d